name: "markdownlint"

on:
  push:
    branches: [master]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]

jobs:
  test:
    name: "Markdownlint"
    runs-on: ubuntu-latest

    steps:
      - name: Check out the Repository
        uses: actions/checkout@v2

      - name: Run markdownlint (mdl)
        uses: bewuethr/mdl-action@master
        with:
          style-file: .github/workflows/markdownlint.rb
