name: pylint

on: ["push", "pull_request"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install --upgrade pylint
          pip install --upgrade -r requirements.txt

      - name: Test with pylint
        run: |
          pylint -E --output-format=colorized easywall
