name: "pylint"

on:
  push:
    branches: [master]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]

jobs:
  test:
    name: "Pylint"
    runs-on: ubuntu-latest

    steps:
      - name: Check out the Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install --upgrade pylint
          pip install --upgrade -r requirements.txt

      - name: Test with pylint
        run: |
          pylint -E --output-format=colorized easywall
