name: "shellcheck"

on:
  push:
    branches: [master]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]

jobs:
  shellcheck:
    name: "ShellCheck"
    runs-on: ubuntu-latest

    steps:
      - name: Check out the Repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt install -y shellcheck
          shellcheck --version

      - name: Test using shellcheck
        run: |
          EXITCODE=0
          for i in $(find . -type f -iname '*.sh') ; do
            echo "testing ${i} ..."
            shellcheck -a -Calways -S style "${i}"
            RC=$?
            if [ "${RC}" -ne 0 ] ; then
              EXITCODE="${RC}"
            fi
            echo ""
          done
          exit "${EXITCODE}"
